# Configure main menu and social menu
#[[main]]
#identifier = "about"
#name = "About"
#url = "/about"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
    name = "archives"
    url = "/archives/"
    weight = -110
    [main.params]
        icon = "archives"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/InsHomePgup/blog-hugo-stack"

[social.params]
icon = "brand-github"

# 添加 RSS 订阅按钮
[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 40

[social.params]
icon = "rss"
