# Configure main menu and social menu
# All items are explicitly defined here to control the order.

[[main]]
    name = "Home"
    url = "/"
    weight = 10
    [main.params]
        icon = "home"

[[main]]
    name = "Search"
    url = "/search/"
    weight = 20
    [main.params]
        icon = "search"

[[main]]
    name = "Archives"
    url = "/archives/"
    weight = 30
    [main.params]
        icon = "archives"

[[main]]
    name = "All Posts"
    url = "/blog/"
    weight = 35
    [main.params]
        icon = "book"

[[main]]
    name = "Links"
    url = "/links/"
    weight = 40
    [main.params]
        icon = "link"

[[main]]
    name = "About"
    url = "/about/"
    weight = 50
    [main.params]
        icon = "braces"


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/InsHomePgup/blog-hugo-stack"

[social.params]
icon = "brand-github"

# 添加 RSS 订阅按钮
[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 40

[social.params]
icon = "rss"