backend:
  name: github
  repo: InsHomePgup/blog-hugo-stack
  branch: main
  base_url: https://blog-cms-oauth-one.vercel.app
  auth_endpoint: auth

media_folder: static/img
public_folder: /img

locale: zh_Hans

collections:
  - name: computer
    label: 计算机
    folder: content/Post/Computer
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: 最后更新, name: last-update, widget: datetime, format: "YYYY-MM-DD", required: false }
      - { label: 草稿, name: draft, widget: boolean, default: true }
      - { label: 权重, name: weight, widget: number, default: 1, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }

  - name: frontend
    label: 前端
    folder: content/Post/front-end
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: 最后更新, name: last-update, widget: datetime, format: "YYYY-MM-DD", required: false }
      - { label: 草稿, name: draft, widget: boolean, default: true }
      - { label: 权重, name: weight, widget: number, default: 1, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }

  - name: git
    label: Git
    folder: content/Post/Git
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: 最后更新, name: last-update, widget: datetime, format: "YYYY-MM-DD", required: false }
      - { label: 草稿, name: draft, widget: boolean, default: true }
      - { label: 权重, name: weight, widget: number, default: 1, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }

  - name: life
    label: 生活
    folder: content/Post/Life
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: 最后更新, name: last-update, widget: datetime, format: "YYYY-MM-DD", required: false }
      - { label: 草稿, name: draft, widget: boolean, default: true }
      - { label: 权重, name: weight, widget: number, default: 1, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }

  - name: readme
    label: 首页文章
    folder: content/Post/README
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: 最后更新, name: last-update, widget: datetime, format: "YYYY-MM-DD", required: false }
      - { label: 草稿, name: draft, widget: boolean, default: true }
      - { label: 权重, name: weight, widget: number, default: 1, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }
